dist: bionic
language: node_js
node_js:
  - 12.16.1
cache: yarn
git:
  depth: false
branches:
  only:
    - develop
    - "/^epic\\/.*$/"
    - "/^release\\/.*$/"
defaults: &defaults
  script: "export CYPRESS_CONFIG=cypress.ci.json && ./ci-scripts/e2e-cypress.sh"
jobs:
  - script: "./build.sh sonar" 
    name: "Validation checks / Unit tests / Sonar"
  - script: "export CYPRESS_CONFIG=cypress.ci.b2b.json &&  export SPA_ENV='ci,b2b' && ./ci-scripts/e2e-cypress.sh -s b2b"
    name: E2E regression tests for B2B
  - script:
    name: "E2E tests for B2C, 1st job"
    env: STAGE_NAME=spa-ci-regression
    <<: *defaults
  - script:
    name: "E2E tests for B2C, 2st job"
    env: STAGE_NAME=spa-ci-regression
    <<: *defaults
  - script:
    name: "E2E tests for B2C, 3rd job"
    env: STAGE_NAME=spa-ci-regression
    <<: *defaults
  - script:
    name: "E2E tests for B2C, 4th job"
    env: STAGE_NAME=spa-ci-regression
    <<: *defaults
addons:
  chrome: stable
  sonarcloud:
    organization: sap
